### ISSUE TITLE
[FEA] Add Python Stubs for Cython/PyBind11 Modules

### ISSUE THREAD

**Issue by mdemoret-nv** [NVIDIA/Morpheus#99]
**Is your feature request related to a problem? Please describe.**
Python modules created with cython/pybind11 do not show up in IDEs and fail all linting which is a poor developer experience.

**Describe the solution you'd like**
Utilize mypy or pybind11-stubgen to create pyi stubs for all C++ generated code. This allows linters and IDEs to pickup and check python code using these modules

**Comment by mdemoret-nv** [comment]
@lobotmcj I haven't seen pytype before. Looks interesting but I'm not sure it has the same functionality of pybind11-stubgen. Can pytype create python stub files from C-extensions?

**Comment by lobotmcj** [comment]
@mdemoret-nv I'll look into it and get back to you

**Comment by lobotmcj** [comment]
@mdemoret-nv pytype does not appear to have the desired functionality either in its documentation or in my testing.

I like Devin's suggestion [here](https://github.com/NVIDIA/Morpheus/pull/100#pullrequestreview-970214970) anyway if the output location limitation becomes an issue.

**Comment by mdemoret-nv** [comment]
Thanks for looking into that. I think that unless it gets to be a problem, we will work with the current layout. If needed we can fork and upstream the changes.
